### ISSUE TITLE
Re-Ordering Membership Types

### ISSUE THREAD

**Issue by roadsunknown** [lcdservices/CiviCRM-CiviAuthenticate#1]
After re-ordering the membership types, the original plugin settings cannot not be adjusted. The SQL statement will load the select in the new order, but with the select disabled, you cannot change the "Membership Type" values previously set.

The scenario I encountered has ~20 membership types, but only 9 map to a Joomla User Group. These 9 types were not initially in order. Plugin was enabled and settings saved. The first 9 types saved. After re-ordering the types, its not possible to reassign without the below workarounds.

Workarounds:
1) Edit the database directly - Table: j25n_extensions, Record/Name Authentication - CiviCRM, Field: params
2) Use browser tools to remove the "disabled" property from the select(s).

**Comment by lcdservices** [comment]
the plugin has undergone a number of updates since this ticket was opened. closing as no longer able to replicate.
