### ISSUE TITLE
#Joomla4 Declaration of JFormRuleCiviMembershipTypes must be compatible with Joomla\CMS\Form\FormRule

### ISSUE THREAD

**Issue by vingle** [lcdservices/CiviCRM-CiviAuthenticate#15]
When CiviAuthenticate is saved in J4.x PHP8.0.8:

**Compile Error: Declaration of JFormRuleCiviMembershipTypes::test(&$element, $value, $group = null, &$input = null, &$form = null) must be compatible with Joomla\CMS\Form\FormRule::test(SimpleXMLElement $element, $value, $group = null, ?Joomla\Registry\Registry $input = null, ?Joomla\CMS\Form\Form $form = null)**

    Exception Stack Trace 

Symfony\Component\ErrorHandler\Error\ FatalError
in[ /Users/admin/Sites/localhost/sitename/plugins/authentication/civicrm/rules/civimembershiptypes.php ](https://wapcepc:8890/administrator/index.php?option=com_plugins&view=plugin&layout=edit&extension_id=10062)(line 38)

       *
       * @return   boolean          True if the value is valid, false otherwise.
       * @since    1.6
       * @throws   JException on invalid rule.
       */
      public function test(&$element, $value, $group = NULL, &$input = NULL, &$form = NULL) {
        /*
         * Here we match the value with a specific format. You may also use any kind of validation,
         * If you need a value of another field as well from the same form then use the following method:
         * $userId = ($input instanceof JRegistry) ? $input->get('id') : '0';
         * this gived you the value of the Id field

**Comment by lcdservices** [comment]
@vingle Can you verify if the PR on #18 fixes this?

**Comment by vingle** [comment]
It does fix this.

**Comment by lcdservices** [comment]
closing with v5.0 release
