### ISSUE TITLE
J4 branch

### ISSUE THREAD

**Issue by aydun** [lcdservices/CiviCRM-CiviAuthenticate#17]
Hi @lcdservices - I've been doing some work on a Joomla4 version here: https://github.com/aydun/CiviCRM-CiviAuthenticate/tree/j4  (sponsored by @vingle)

There doesn't seem to be a way to request the creation of a new branch on your repo via a PR, but if you could create a j4 branch, I can then PR changes to that.

**Comment by lcdservices** [comment]
No problem -- just did that. Thanks for putting in work on this!

**Comment by aydun** [comment]
Thanks!

**Comment by vingle** [comment]
> (sponsored by @vingle)

Thanks to _The Person Centred Association_, and the _World Association for Person Centered & Experiential Psychotherapy & Counseling_ for funding the work.

**Comment by vingle** [comment]
> (sponsored by @vingle)

Thanks both – and thanks to _The Person Centred Association_, and the _World Association for Person Centered & Experiential Psychotherapy & Counseling_ for funding the work.
