### ISSUE TITLE
User Not Removed from Group

### ISSUE THREAD

**Issue by roadsunknown** [lcdservices/CiviCRM-CiviAuthenticate#3]
Users are not removed from the Joomla group that is mapped to a Membership Level when that membership level subscription has been deleted from the user's account in CiviCRM if the user has no other membership levels assigned.

The exception, is if another membership level added to assigned to the user, then the new Joomla group will be added to the Joomla user account and the deleted membership group removed.

**Comment by lcdservices** [comment]
closing per last comment and no further response.
