### ISSUE TITLE
Membership types being assigned to wrong user groups

### ISSUE THREAD

**Issue by vanboke** [lcdservices/CiviCRM-CiviAuthenticate#5]
I am having an issue where I am trying to assign certain membership types to certain groups.  The problem is that most of the membership types are being assigned to the wrong group upon user login.  Oddly though I have a few membership types that are mapping correctly to the corresponding user groups, and a few more don't map to any user groups.

I was running version 3.0.5, and just upgraded to 3.0.7.  I am having the same issue.

I had modified the civicrm.xml and civicrm.php files to add more options for membership types as I have 19 of them.  I thought maybe I messed something up, and in double checking the code could not find any issues.  After upgrading to version 3.0.7 I haven't even re-applied those edits to increase the number of membership types available, and I am still having the issues.

Do you have any thoughts on what is going wrong?  I am going to continue researching this further, but thought I would ask.

**Comment by vanboke** [comment]
Just an FYI on this issue.  I just looked at the DB, and looked at the mappings that are being saved there for the plugin, and then looking at the CiviCRM membership types table and Joomla user groups table.  The mappings look to be all correct.  I can't for the life of me figure out why this isn't working on the website though.

**Comment by lcdservices** [comment]
I will investigate and let you know what I see.

**Comment by vanboke** [comment]
Thank you for investigating this.  I am also having some odd cases of people with memberships logging in and not getting assigned to the corresponding Joomla user group.  I am not sure how this is possible.  I have tried stepping through the code, and it looks like it should work unless it is not getting the fact that they are indeed a member from CiviCRM.  

Any thoughts on what could cause that?

**Comment by vanboke** [comment]
Sorry to continue to post new information here, while I am sure you are looking into other things I have posted.  However, I have found what I think it another bug.

It appears that the user group is not properly adding after the session expires and they go to log back in.  This is what I am seeing happening at the moment:

They are logged in, and accessing content fine for their user group.
The user does not log out, and the Joomla session expires.
They browse the website, find they are not logged in, and log back into the website.
They are logged in, but no longer have access to the content they were accessing, as they are no longer part of that user group.
If they log out, and then log back in, they are then added to the user group properly and can access the content they should be able to access.

Any thoughts on this issue, or any of the previous ones?

**Comment by vanboke** [comment]
I don't mean to be a bother, but I wanted to know if you have been able to do look into any of these issues yet?  Is there anything I can do to help?  I can give you access to our website if you need it for debugging.  I haven't coded for years, but I can try to help with that if needed as well.

I just need to work through these issues soon.  Any update would be helpful.  Thanks.

**Comment by lcdservices** [comment]
honestly, I'm pretty busy with client work. so I'm not sure when I'll have a chance to work through this. hopefully later this week, but I can't say for sure.

**Comment by vanboke** [comment]
I do completely understand issues with not having enough time.  If it helps at all though we would be happy to pay you for your time.  Let me know if that is an option, and thank you for any time you can spend on this.

**Comment by vanboke** [comment]
Is there any possibility at all of getting help fixing this plugin?  I have repeatable issues on my end that I would like to address, but I don't have the expertise to address them.  I would be more than willing to pay for your time to fix this plugin.  Please respond and let me know your thoughts.

**Comment by lcdservices** [comment]
the plugin has undergone a number of updates since this ticket was opened. closing as no longer able to replicate.
