### ISSUE TITLE
Pending Membership Allows User to access Expired Membership Form

### ISSUE THREAD

**Issue by nzampella** [lcdservices/CiviCRM-CiviAuthenticate#6]
unning:
J!:  3.4.0
Php:  5.4.37
MySQL: 5.5.41
CiviCRM: 4.5.8

I just received a membership request and payment on someone that had previously created a request, but it was still pending, since they evidently never went forward with the online payment.

Evidently the plugin gave them the Expired Membership contribution/renewal page when they should have gotten the 'No Valid Membership' menu item.  
![civiauth1](https://cloud.githubusercontent.com/assets/11995082/7203442/c2de990c-e4e8-11e4-8b32-be184a0b1d9a.jpg)
![civiauth2](https://cloud.githubusercontent.com/assets/11995082/7203445/c482f6e0-e4e8-11e4-9b8d-892439fe7f51.jpg)
![civiauth3](https://cloud.githubusercontent.com/assets/11995082/7203448/c5e034ee-e4e8-11e4-9b45-67c6c3614f08.jpg)
![civiauth4](https://cloud.githubusercontent.com/assets/11995082/7203450/c7520c62-e4e8-11e4-9308-19192ebf1c09.jpg)
![civiauth5](https://cloud.githubusercontent.com/assets/11995082/7203451/c8a0c856-e4e8-11e4-8593-13e68e0c57dc.jpg)

**Comment by lcdservices** [comment]
the plugin has undergone a number of updates since this ticket was opened. can you still replicate the issue?

**Comment by nzampella** [comment]
I haven't checked in a while unfortunately,    I'll download the files, and put them up on the site to install and see.

**Comment by nzampella** [comment]
Oy ...  well, better late than never.   Installed the last updates, and it works fine.   

I do have another question ... will this plugin still work under Joomla 4.x ??

**Comment by lcdservices** [comment]
I don't know yet. I haven't done any testing.
If you want to open a new ticket, I'll try to work on that in the next few weeks to see what may need to be done.
