### ISSUE TITLE
Usergroup assign dont work properly when login/logout several time

### ISSUE THREAD

**Issue by amjulash** [lcdservices/CiviCRM-CiviAuthenticate#8]
Hi,

On our website when user login, logout several time user group assignments in "Membership Type Access Control" always dont work properly. Sometime the usergroup are assigned correctly by "CiviCRM-CiviAuthenticate" plugin then when again login later its remove user from the usergroup. Its keep looping like that.

I tried that on several joomla website and on two server. But same issue.

We are using latest joomla 3.4.5 and civicrm 4.6.9. You can check the issue here http://amjulash.com/project/civi/ with username/password: demo1/demo1

Please help us.

Thanks
Julash

**Comment by lcdservices** [comment]
the plugin has undergone a number of updates since this ticket was opened. closing as no longer able to replicate.
